### ISSUE TITLE
Dateien auf Desktop erzeugt

### ISSUE THREAD

**Issue by ManuelHu** [engeniousproject/engenious.ContentTool#1]
Bei mir erzeuugt das Kompilieren des `SamepleClient`s einen Ordner auf dem Windows-Desktop, der verschatelt eine Datei Content.dat enthält.

`C:\Users\$USER\Desktop\engenious.UI\SampleClient\Content\obj\Debug\Content.dat`

Ich hoffe das Issue ist hier richtig beim Contenttool

**Comment by jvbsl** [comment]
Issue ist hier richtig.
Wird auf den Vatertag spätestens gefixt....Nächstes Jahr

**Comment by jvbsl** [comment]
Sollte eigentlich durch den komplett umbau vom ContentTool schon längers gefixt sein. Falls nicht neues issue aufmachen
