### ISSUE TITLE
Neu erstellter Ordner heißt "New Folder"

### ISSUE THREAD

**Issue by TheBlubb14** [engeniousproject/engenious.ContentTool#2]
Wenn ich im Content Tool auf `Content` im Treeview rechtsklicke und auf `Add`, `New Folder` klicke und dem Ordner einen passenden Namen gebe, so wird im Dateisystem ein Ordner mit dem Namen `New Folder` angelegt. Ein speichern, oder Neubauen des Contents bringt auch nichts.
Getestet mit Version `engenious.ContentTool.0.3.0.30-alpha`

**Comment by jvbsl** [comment]
Sollte mit dem ganzen umbau gefixt sein...
Und durch https://github.com/engeniousproject/engenious.ContentTool/pull/10/commits/19c2a0c26abb2bfbbeff9673093f8ef32e122caa geht auch das context menu wieder
